/**
 * rxx —— shim 脚本生成 + PATH 管理
 *
 * `rxx init` 安装一个服务时,在 ~/.rxx/bin/ 下生成一个 shim 脚本:
 *   ~/.rxx/bin/rxcrm  (POSIX sh,chmod 500)
 *   ~/.rxx/bin/rxcrm.cmd  (Windows 批处理)
 *
 * 用户打 `rxcrm orders list` → 命中 shim → exec rxx run rxcrm orders list。
 *
 * PATH 管理:~/.rxx/bin 不在 PATH 时,幂等写入 shell rc 文件(标记块包裹)。
 *   方案 A(fnm/pyenv/volta 模式):显式脚本转发,最可靠。
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  chmodSync,
  rmSync,
  unlinkSync,
  renameSync,
  openSync,
  fsyncSync,
  closeSync,
  realpathSync,
} from "node:fs";
import { homedir } from "node:os";
import { join, dirname } from "node:path";
import { randomBytes } from "node:crypto";
import { getRxBinDir } from "./config.js";
import { assertSafeServiceName } from "./security.js";

/** PATH rc 文件标记块(幂等写入用)。仅 shim.ts 用,故定义在此。 */
const PATH_MARKER_START = "# >>> rxx bin >>>";
const PATH_MARKER_END = "# <<< rxx bin <<<";

// ============================================================================
// shim 脚本生成
// ============================================================================

/**
 * 生成并写入一个服务的 shim(POSIX + Windows)。
 * update 时会覆盖旧 shim——但旧 shim 是 chmod 500(只读),
 * writeFileSync 无法直接覆盖,所以先 unlink 再写。
 */
export function writeShim(serviceName: string): void {
  // 纵深防御:写入前 assert 服务名合法(防 shell 注入)
  assertSafeServiceName(serviceName);

  const binDir = getRxBinDir();
  mkdirSync(binDir, { recursive: true });

  // POSIX sh 脚本(macOS/Linux/git-bash 通用)
  const shPath = join(binDir, serviceName);
  // 先删旧的(可能是 chmod 500 只读文件,writeFileSync 会 EACCES)
  try {
    unlinkSync(shPath);
  } catch {
    /* 不存在则忽略 */
  }
  writeFileSync(shPath, posixShim(serviceName), "utf8");
  try {
    chmodSync(shPath, 0o500); // r-x------  仅 owner 可执行
  } catch {
    /* 某些文件系统不支持 chmod,忽略 */
  }

  // Windows 批处理(服务名已 assert 为安全字符,无需额外 escape)
  const cmdPath = join(binDir, `${serviceName}.cmd`);
  try {
    unlinkSync(cmdPath);
  } catch {
    /* 不存在则忽略 */
  }
  writeFileSync(cmdPath, windowsCmdShim(serviceName), "utf8");
}

/** 移除一个服务的 shim。 */
export function removeShim(serviceName: string): void {
  // 纵深防御:独立校验名字(不依赖 removeService 先执行)
  assertSafeServiceName(serviceName);
  const binDir = getRxBinDir();
  const shPath = join(binDir, serviceName);
  const cmdPath = join(binDir, `${serviceName}.cmd`);
  for (const p of [shPath, cmdPath]) {
    if (existsSync(p)) {
      try {
        rmSync(p);
      } catch {
        /* 忽略删除失败 */
      }
    }
  }
}

/** POSIX sh shim 内容。 */
function posixShim(serviceName: string): string {
  // serviceName 已通过 assertSafeServiceName(/^[a-z][a-z0-9-]{1,63}$/),
  // 不含 shell 元字符。仍用双引号包裹做 defense-in-depth。
  return [
    "#!/bin/sh",
    `# rxx shim → rxx run ${serviceName}  (generated by 'rxx init', do not edit)`,
    "# 动态转发:所有参数透传给 rxx run",
    `exec rxx run "${serviceName}" "$@"`,
    "",
  ].join("\n");
}

/** Windows 批处理 shim 内容。 */
function windowsCmdShim(serviceName: string): string {
  return [
    "@echo off",
    `:: rxx shim → rxx run ${serviceName}  (generated by 'rxx init')`,
    `rxx run ${serviceName} %*`,
    "",
  ].join("\r\n");
}

// ============================================================================
// PATH 管理
// ============================================================================

/** 检测 ~/.rxx/bin 是否在 PATH 中(realpath 解软链后比较)。 */
export function isInPath(): boolean {
  const binDir = getRxBinDir();
  const path = process.env.PATH ?? "";
  const sep = process.platform === "win32" ? ";" : ":";
  return path.split(sep).some((p) => pathEq(p, binDir));
}

/**
 * 比较两个路径是否等价:先 realpath 解软链,再字面 + 尾斜杠归一比较。
 *
 * realpath 解软链很重要:用户可能 `ln -s /Volumes/x/bin ~/.rxx/bin`,
 * 此时 PATH 里的字面路径与 RX_BIN_DIR 不同但指向同一目录。
 * 不 resolve 会误判"不在 PATH"→ 重复写 PATH 块。
 */
function pathEq(a: string, b: string): boolean {
  const resolve = (p: string): string => {
    try {
      return realpathSync(p).replace(/\/+$/, "");
    } catch {
      return p.replace(/\/+$/, "");
    }
  };
  return resolve(a) === resolve(b);
}

/**
 * 确保 ~/.rxx/bin 在 PATH 中。幂等写入 shell rc 文件(标记块包裹)。
 *
 * @returns 写入了哪个文件(需要 source);null=已在 PATH 或写入失败
 */
export function ensureInPath(): string | null {
  if (isInPath()) return null;

  const rcFile = detectRcFile();
  if (!rcFile) return null;

  const existing = existsSync(rcFile) ? readFileSync(rcFile, "utf8") : "";
  // 已有完整标记块(start + end)→ 不重复写
  if (existing.includes(PATH_MARKER_START) && existing.includes(PATH_MARKER_END)) return null;

  // 残缺块处理:有 start 无 end(或反之)→ 先清掉残缺行再写完整块
  const cleaned = stripPartialMarkerBlock(existing);
  const block = [
    "",
    PATH_MARKER_START,
    `export PATH="$HOME/.rxx/bin:$PATH"`,
    PATH_MARKER_END,
    "",
  ].join("\n");

  atomicWriteRc(rcFile, cleaned.replace(/\n*$/, "\n") + block);
  return rcFile;
}

/** 删除残缺的标记块(只有 start 没 end,或反之)。完整块保留。 */
function stripPartialMarkerBlock(content: string): string {
  const hasStart = content.includes(PATH_MARKER_START);
  const hasEnd = content.includes(PATH_MARKER_END);
  if (hasStart && hasEnd) return content; // 完整,不动
  if (!hasStart && !hasEnd) return content; // 都没有,不动
  // 残缺:删掉存在的那个标记行(以及它到另一标记间的行,避免遗留)
  const lines = content.split("\n");
  const out: string[] = [];
  let skipping = false;
  for (const line of lines) {
    if (line === PATH_MARKER_START || line === PATH_MARKER_END) {
      skipping = !skipping;
      continue;
    }
    if (skipping) continue;
    out.push(line);
  }
  return out.join("\n");
}

/** 原子写 rc 文件(fsync + rename),防 crash 损坏用户的 rc。 */
function atomicWriteRc(filePath: string, content: string): void {
  mkdirSync(dirname(filePath), { recursive: true });
  const rand = randomBytes(6).toString("hex");
  const tmp = `${filePath}.tmp.${process.pid}.${rand}`;
  let fd: number | undefined;
  try {
    fd = openSync(tmp, "w");
    writeFileSync(fd, content, "utf8");
    fsyncSync(fd);
    closeSync(fd);
    fd = undefined;
    renameSync(tmp, filePath);
  } catch (err) {
    if (fd !== undefined) {
      try {
        closeSync(fd);
      } catch {
        /* 忽略 */
      }
    }
    try {
      unlinkSync(tmp);
    } catch {
      /* 忽略 */
    }
    throw err;
  }
}

/** 检测当前 shell 的 rc 文件。 */
function detectRcFile(): string | null {
  const home = homedir();
  const shell = process.env.SHELL ?? "";

  // fish(配置文件在 ~/.config/fish/)
  const fishConfig = join(home, ".config", "fish", "config.fish");
  if (shell.includes("fish") || existsSync(fishConfig)) return fishConfig;

  // zsh
  const zshrc = join(home, ".zshrc");
  if (shell.includes("zsh") || existsSync(zshrc)) return zshrc;

  // bash
  const bashrc = join(home, ".bashrc");
  if (shell.includes("bash") || existsSync(bashrc)) return bashrc;

  // 兜底:bash_profile
  const bashProfile = join(home, ".bash_profile");
  return existsSync(bashProfile) ? bashProfile : bashrc;
}
