/**
 * @renxqoo/agent-data-cli/skills —— 命令文档自动生成(gen)
 *
 * 设计依据:docs/06-skills.md "自动文档生成"、"命令签名生成规则"。
 * 核心机制:AUTO-GEN 标记块(preserved regions)。
 *   - 标记块内:从 defineCommands 的 spec 自动生成(签名表 + 参数表),每次 gen 覆盖,人不要手改
 *   - 标记块外:人写的语义内容(何时用/错误处理),gen 永不触碰
 *
 * 两种策略(都用,决策清单 #15):
 *   - 策略 A(增量):只生成 ## 命令 + ### 参数说明 两节,塞进标记块 → gen <name>
 *   - 策略 B(骨架):首次吐整份 SKILL.md(带 {{FILL}} 占位),后续只刷标记块 → gen <name> --init
 */

import { compileCommandSchema, type ArgumentDescriptor } from "../command-schema.js";
import type { CommandArgs, CommandSpec, DefineCliOptions } from "../types.js";
import { stringify as stringifyYaml } from "yaml";
import { InternalError } from "../errs/index.js";
import { validateSkillName } from "./path-guard.js";

// ============================================================================
// i18n:生成内容的中英文文案表
// ============================================================================

/** 生成内容支持的语言。 */
export type GenLang = "en" | "zh";

/** 模板/表头文案(中英双语)。 */
const GEN_STRINGS: Record<
  GenLang,
  {
    commandsHeading: string;
    commandsHeader: string;
    argTableHeader: string;
    autogenComment: string;
    skeletonFillIntro: string;
    skeletonFillDesc: string;
    whenToUseHeading: string;
    whenToUseHeader: string;
    whenToUseFill: string;
    prereqHeading: string;
    prereqLoggedIn: string;
    errorHeading: string;
    errorHeader: string;
    errorNotFoundFill: string;
    errorNetwork: string;
    requiredYes: string;
    requiredNo: string;
  }
> = {
  en: {
    commandsHeading: "## Commands",
    commandsHeader: "| Operation | Command |",
    argTableHeader: "| Argument | Type | Required | Default | Description |",
    autogenComment:
      "<!-- This block is auto-generated by `rxcli skills gen`; do not edit by hand -->",
    skeletonFillIntro: "{{FILL: intro — what operations are supported}}",
    skeletonFillDesc:
      "{{FILL: one sentence describing when to use this — the agent matches it semantically against user intent}}",
    whenToUseHeading: "## When to use",
    whenToUseHeader: "| User says | Command |",
    whenToUseFill: '{{FILL: "list orders"}}',
    prereqHeading: "## Prerequisites",
    prereqLoggedIn: "Logged in:",
    errorHeading: "## Error handling",
    errorHeader: "| Error | Handling |",
    errorNotFoundFill: "{{FILL: record does not exist, use list to find a valid ID}}",
    errorNetwork: "retry later",
    requiredYes: "yes",
    requiredNo: "no",
  },
  zh: {
    commandsHeading: "## 命令",
    commandsHeader: "| 操作 | 命令 |",
    argTableHeader: "| 参数 | 类型 | 必填 | 默认 | 说明 |",
    autogenComment: "<!-- 本区块由 `rxcli skills gen` 自动生成,不要手改 -->",
    skeletonFillIntro: "{{FILL: 简介 —— 支持哪些操作}}",
    skeletonFillDesc: "{{FILL: 一句话描述何时用 —— agent 靠它语义匹配用户意图}}",
    whenToUseHeading: "## 何时用",
    whenToUseHeader: "| 用户说 | 命令 |",
    whenToUseFill: '{{FILL: "查订单"}}',
    prereqHeading: "## 前置条件",
    prereqLoggedIn: "已登录:",
    errorHeading: "## 错误处理",
    errorHeader: "| 错误 | 处理 |",
    errorNotFoundFill: "{{FILL: 记录不存在,用 list 查有效 ID}}",
    errorNetwork: "稍后重试",
    requiredYes: "是",
    requiredNo: "否",
  },
};

// ============================================================================
// AUTO-GEN 标记块
// ============================================================================

export const AUTOGEN_START = "<!-- AUTO-GEN:START commands -->";
export const AUTOGEN_END = "<!-- AUTO-GEN:END -->";

// ============================================================================
// 从 defineCli 的 commands/namespaces 提取所有命令(扁平化)
// ============================================================================

interface FlatCommand {
  /** 完整命令路径(如 'list' 或 'orders list')。 */
  path: string;
  spec: CommandSpec;
}

/** 把 defineCli 的 commands + namespaces 扁平化成命令列表。 */
export function flattenCommands(
  options: Pick<DefineCliOptions<any>, "commands" | "namespaces">,
): FlatCommand[] {
  const out: FlatCommand[] = [];
  for (const [cmdName, spec] of Object.entries(options.commands ?? {})) {
    out.push({ path: cmdName, spec });
  }
  if (options.namespaces) {
    for (const [nsName, group] of Object.entries(options.namespaces)) {
      for (const [cmdName, spec] of Object.entries(group)) {
        out.push({ path: `${nsName} ${cmdName}`, spec });
      }
    }
  }
  return out;
}

// ============================================================================
// 单个命令的签名 + 参数表生成
// ============================================================================

/** 生成单个命令的签名行(如 `rxcli-orders list [--limit <number>] [--status <string>]`)。 */
export function signatureLine(binName: string, cmd: FlatCommand): string {
  const sig = compileCommandSchema(cmd.spec.name, cmd.spec.args, cmd.spec.policy).signature;
  const pos = sig.positionals.join(" ");
  const opts = sig.options.join(" ");
  return [`${binName} ${cmd.path}`, pos, opts].filter(Boolean).join(" ").trim();
}

/** 生成参数说明表(markdown)。 */
export function argsTable(argsSpec: CommandArgs | undefined, lang: GenLang = "en"): string {
  if (!argsSpec) return "";
  const t = GEN_STRINGS[lang];
  const rows = compileCommandSchema("skill-doc", argsSpec).descriptors.map((argument) => {
    return `| ${escapeCell(argumentTableLabel(argument))} | ${argument.type} | ${argument.required ? t.requiredYes : t.requiredNo} | ${escapeCell(formatDefault(argument.defaultValue))} | ${escapeCell(argument.description ?? "—")} |`;
  });
  if (rows.length === 0) return "";
  return [t.argTableHeader, "|------|------|:----:|------|------|", ...rows].join("\n");
}

/** 参数在签名里的展示形态；表格使用位置参数名或 kebab-case flag 名。 */
function argumentTableLabel(argument: ArgumentDescriptor): string {
  if (argument.positional) {
    return argument.required ? `<${argument.name}>` : `[<${argument.name}>]`;
  }
  if (argument.type === "boolean") return `--${argument.flagName}`;
  return `--${argument.flagName} <${argument.type}>`;
}

function formatDefault(def: unknown): string {
  if (def === undefined) return "—";
  if (typeof def === "string") return def;
  return String(def);
}

/**
 * 转义 markdown 表格单元格:| → \|、换行 → 空格(BUG-13)、` → &#96;(M9,非 code-span 单元格里
 * 反引号会开启不平衡的 code span,markdown 不支持反斜杠转义反引号)。
 * 避免含 | 或 \n 的 default/desc 把表格撑出多列或多行。
 */
function escapeCell(value: unknown): string {
  const s = value === undefined || value === null ? "—" : String(value);
  return s.replace(/\|/g, "\\|").replace(/`/g, "&#96;").replace(/\r?\n/g, " ");
}

// ============================================================================
// scope 过滤(per-skill 命令分片)
// ============================================================================

/**
 * 按 scope 过滤扁平化命令列表。
 *
 * scope 匹配命令路径的**第一段**(namespace 名,或顶层命令名本身):
 *   - `"life weather"` → 第一段 `"life"` → scope 含 `"life"` 则保留
 *   - `"today"`(顶层命令,path 无空格) → 第一段 `"today"` → scope 含 `"today"` 则保留
 *
 * @param scope 命令路径第一段的允许集合;undefined / 空数组 → 不过滤(返回全部)
 */
function filterByScope(cmds: FlatCommand[], scope?: string[]): FlatCommand[] {
  if (!scope || scope.length === 0) return cmds;
  const allow = new Set(scope);
  // path 第一段 = namespace 名(如 "life weather" → "life")或顶层命令名(如 "today")。
  // split(" ", 1)[0] 在 noUncheckedIndexedAccess 下是 string | undefined,兜底空串(永不在 allow 中)。
  return cmds.filter((c) => allow.has(c.path.split(" ", 1)[0] ?? ""));
}

// ============================================================================
// AUTO-GEN 块内容(## 命令 + ### 参数说明)
// ============================================================================

/** 生成 AUTO-GEN 块的完整内容(策略 A)。 */
export function generateAutogenBlock(
  binName: string,
  options: Pick<DefineCliOptions<any>, "commands" | "namespaces">,
  lang: GenLang = "en",
  scope?: string[],
): string {
  const cmds = filterByScope(flattenCommands(options), scope);
  if (cmds.length === 0) return "";
  const t = GEN_STRINGS[lang];

  const lines: string[] = [];
  // ## 命令表(操作 / 命令)—— 仅命令索引(签名 + 描述)。参数细节不在此处展开。
  lines.push(t.commandsHeading);
  lines.push("");
  lines.push(t.commandsHeader);
  lines.push("|------|------|");
  for (const cmd of cmds) {
    const desc = escapeCell(cmd.spec.description ?? "");
    // M9: code spans do not honor backslash escapes; signatures never contain
    // backticks, so the former `\`` escaping was both useless and harmful. escapeCell
    // neutralizes backticks for the non-code-span desc cell.
    const sig = escapeCell(signatureLine(binName, cmd));
    lines.push(`| ${desc} | \`${sig}\` |`);
  }

  const structured = cmds.filter((cmd) => cmd.spec.args?.type === "json");
  if (structured.length > 0) {
    lines.push("");
    lines.push(lang === "zh" ? "### JSON 参数" : "### JSON arguments");
    lines.push("");
    lines.push(
      lang === "zh"
        ? "| 命令 | 输入方式 | Schema / 示例 |"
        : "| Command | Input | Schema / example |",
    );
    lines.push("|------|------|------|");
    for (const cmd of structured) {
      lines.push(
        `| \`${escapeCell(cmd.path)}\` | \`--input / --input-file / stdin\` | ` +
          `\`${escapeCell(`${binName} ${cmd.path} --input-schema`)}\` / ` +
          `\`${escapeCell(`${binName} ${cmd.path} --input-example`)}\` |`,
      );
    }
    lines.push("");
    lines.push(
      lang === "zh"
        ? "必须提供一个完整 JSON 文档；JSON 参数不能与业务 flags 或位置参数合并。"
        : "Provide one complete JSON document; JSON arguments cannot be merged with business flags or positional operands.",
    );
  }

  return lines.join("\n").trimEnd();
}

// ============================================================================
// 策略 A:刷新已有 SKILL.md 的 AUTO-GEN 块
// ============================================================================

/**
 * 刷新 SKILL.md 内容的 AUTO-GEN 块(策略 A)。
 * - 文件已有 AUTO-GEN 块:替换块内容,块外语义内容不动
 * - 文件无 AUTO-GEN 块(或不存在):返回带块的新内容(块接在末尾)
 *
 * @param existing 已有 SKILL.md 内容(空字符串表示无)
 * @returns 新的 SKILL.md 内容
 */
export function refreshAutogen(
  existing: string,
  binName: string,
  options: Pick<DefineCliOptions<any>, "commands" | "namespaces">,
  lang: GenLang = "en",
  scope?: string[],
): string {
  assertAutogenMarkers(existing);
  const t = GEN_STRINGS[lang];
  const block = generateAutogenBlock(binName, options, lang, scope);
  const fullBlock = `${AUTOGEN_START}\n${t.autogenComment}\n${block}\n${AUTOGEN_END}`;

  if (existing.includes(AUTOGEN_START)) {
    // 替换已有块:只替换 AUTO-GEN 区域,M10 不再 trimEnd 整份文档(避免动到块外尾随内容)。
    const regex = new RegExp(
      `${escapeRegex(AUTOGEN_START)}[\\s\\S]*?${escapeRegex(AUTOGEN_END)}`,
      "g",
    );
    const replaced = existing.replace(regex, fullBlock);
    return replaced.endsWith("\n") ? replaced : `${replaced}\n`;
  }

  // 无块:接在已有内容末尾。M10 不再 trimStart 整份文档(避免剥掉用户的 frontmatter/标题前导空白),
  // 仅保证块与已有内容之间有一个空行分隔。
  const separator =
    existing.length === 0 || existing.endsWith("\n\n")
      ? ""
      : existing.endsWith("\n")
        ? "\n"
        : "\n\n";
  return `${existing}${separator}${fullBlock}\n`;
}

// ============================================================================
// 策略 B:首次生成整份 SKILL.md 骨架(带 {{FILL}} 占位)
// ============================================================================

/** 生成整份 SKILL.md 骨架(策略 B,首次 --init 用)。 */
export function generateSkillSkeleton(
  skillName: string,
  description: string,
  binName: string,
  options: Pick<DefineCliOptions<any>, "commands" | "namespaces">,
  lang: GenLang = "en",
  scope?: string[],
): string {
  validateSkillName(skillName);
  const t = GEN_STRINGS[lang];
  const block = generateAutogenBlock(binName, options, lang, scope);
  const frontmatter = stringifyYaml({
    name: skillName,
    description: description || t.skeletonFillDesc,
    metadata: { requires: { bins: [binName] }, category: "business" },
  }).trimEnd();
  return `---
${frontmatter}
---

# ${skillName}

${t.skeletonFillIntro}

${AUTOGEN_START}
${t.autogenComment}
${block}
${AUTOGEN_END}

${t.whenToUseHeading}

${t.whenToUseHeader}
|--------|------|
| ${t.whenToUseFill} | \`${binName} list\` |

${t.prereqHeading}

- ${t.prereqLoggedIn} \`${binName} auth status\`

${t.errorHeading}

${t.errorHeader}
|------|------|
| \`not_found\` / exit 1 | ${t.errorNotFoundFill} |
| exit 4 network error | ${t.errorNetwork} |
`;
}

// ============================================================================
// 辅助
// ============================================================================

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function assertAutogenMarkers(content: string): void {
  const starts = content.split(AUTOGEN_START).length - 1;
  const ends = content.split(AUTOGEN_END).length - 1;
  const startIndex = content.indexOf(AUTOGEN_START);
  const endIndex = content.indexOf(AUTOGEN_END);
  const valid =
    (starts === 0 && ends === 0) ||
    (starts === 1 && ends === 1 && startIndex >= 0 && endIndex > startIndex);
  if (!valid) {
    throw new InternalError({
      subtype: "contract_violation",
      message: "SKILL.md AUTO-GEN markers are missing, duplicated, or out of order",
    });
  }
}
